networks:
  surface-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

services:
  nginx:
    image: nmsbdocker/surface-nginx:v1.0.0
    container_name: surface-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./api/static:/home/app/web/staticfiles
      - ./data:/home/app/web/data
    env_file:
      - api/production.env
    ports:
      - 8080:80
    depends_on:
      - api
    networks:
      - surface-net

  cache:
    container_name: surface-cache
    image: memcached
    restart: unless-stopped
    networks:
      - surface-net

  redis:
    container_name: surface-redis
    image: redis
    restart: unless-stopped
    networks:
      - surface-net

  postgres:
    container_name: surface-database
    image: timescale/timescaledb-postgis:2.3.0-pg13
    shm_size: 4g
    restart: unless-stopped
    env_file:
      - api/production.env
    volumes:
      - ./:/app
      - ./data/postgresql:/var/lib/postgresql/data
      - ./data/shared:/data/shared
      - ./data/backup:/data/backup
      - ./backup_restore_dumps:/restore_dumps
      - ./pg_hba.custom.conf:/etc/postgresql/pg_hba.custom.conf
    ports:
      - 5432:5432
    command:
      - "postgres"
      - "-c"
      - "max_locks_per_transaction=512"
      - "-c"
      - "hba_file=/etc/postgresql/pg_hba.custom.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    networks:
      - surface-net

  api:
    image: nmsbdocker/surface-base:v1.0.0-beta
    container_name: surface-api
    command: ./startup.sh
    env_file:
      - api/production.env
    restart: unless-stopped
    volumes:
      - ./api:/surface
      - ./data/media:/data/media
      - ./data/shared:/data/shared
      - ./data/backup:/data/backup
      - ./data/exported_data:/data/exported_data
      - ./data/documents:/data/documents
    depends_on:
      - postgres
      - cache
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    networks:
      - surface-net

  celery_worker:
    image: nmsbdocker/surface-base:v1.0.0-beta
    container_name: surface-celery-worker
    command: /home/surface/.local/bin/celery -A tempestas_api worker -l info
    env_file:
      - api/production.env
    restart: unless-stopped
    volumes:
      - ./api:/surface
      - ./data/documents/ingest:/data/documents/ingest
      - ./data/exported_data:/data/exported_data
      - ./data/shared:/data/shared
      - ./data/backup:/data/backup
    depends_on:
      - api
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    networks:
      - surface-net

  celery_beat:
    image: nmsbdocker/surface-base:v1.0.0-beta
    container_name: surface-celery-beat
    restart: unless-stopped
    command: /home/surface/.local/bin/celery -A tempestas_api beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - api/production.env
    volumes:
      - ./api:/surface
      - ./data/postgresql:/data
    depends_on:
      - api
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1M"
        max-file: "10"
    networks:
      - surface-net